export default function Head() {
  return (
    <>
      <title>Alchemy Asset Tool</title>
      <link rel="icon" href="./images/alchemyfabicon.png" style={{width:'100%'}}/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      <meta content="width=device-width, initial-scale=1" name="viewport" />
    </>
  )
}
