type IAssets = {
    _id:string;
    id: string;
    assettagid: string;
    purchasefrom: string;
    assignto: string;
    brand: string;
    model: string;
    serialno?: string;
    description?: string;
    purchasedate?: number;
    cost?: string;
    site?: string;
    ram?: string;
    processor?: string;
    category?: string;
    department: string;
    name:string;
    assigndate:string;
    disktype:string;
    remarks:string;
    courierdate:string;
    status:string;
    courierid:string;
    assignmode:string;
    employeeId:string;
    clients:string;
    projectName:string;
    location:string;
    mobile:string;
    position:string;
    email:string;
    workLocation:string;
    address:string;
    sbuHead:string;
    clientsLob:string;
    returndate:number;
  };
  
  export type { IAssets } ;
  